export const warriors = [
  "Alex Ryan Harkins",
  "Andrea Espinosa",
  "Ashley Lieble",
  "Bill Cook",
  "Bob Swank",
  'Captain Carl Davis',
  "Connie Jacobi",
  "Cyd Donaldson-Sprowel",
  "Donna Morris",
  "Ed Fliss",
  "Ellen D. Ross",
  "Fran Kirkland",
  "Jack Hathmann",
  "Jesse Linder",
  "Joe Henley",
  "Kennith Brown",
  "Kurt Kuiser",
  "Melvin Due",
  "Michael Hesselback Jr",
  "Owain Phyfe",
  "Red Pruitt",
  "Renee Ewart",
  "Richard C. Mintzlaff",
  "Sandy Goodall",
  "Terry N. Sofian",
  "Tim Robinson",
  "Tim Shepherd",
];
